# Generated by Django 4.0.6 on 2022-07-21 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='organization_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='main.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='index',
            field=models.IntegerField(verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_deleted',
            field=models.BooleanField(verbose_name='Удалено ли'),
        ),
    ]
